import { defineRouting } from 'next-intl/routing'

import {
  DEFAULT_LOCALE,
  LOCALES,
  UI_DEFAULT_LOCALE,
  type Locale,
} from '@/core/i18n/locales'

/**
 * Per-route, per-locale URL segments.
 *
 * Source-of-truth for editor-facing changes lives in
 * `i18n/pathnames.json` and is regenerated by
 * `scripts/translate-pathnames.ts`. The literal-typed object below is
 * what next-intl actually consumes; `pathnames.json` is kept in sync
 * by hand or via the script and exists so future runs of the
 * translator can diff against it.
 *
 * Dynamic routes ([slug]) reuse the localised first segment in front
 * of the placeholder. The slug itself is per-locale via Sanity
 * (`organQuery` filters on `language == $locale`), so the routing
 * layer only has to translate the first segment.
 */
export const pathnames = {
  '/': '/',
  '/about': {
    en: '/about',
    nl: '/over-mij',
    de: '/ueber-mich',
    fr: '/bio',
    es: '/sobre-mi',
    it: '/chi-sono',
    pt: '/sobre-mim',
    hi: '/परिचय',
    ja: '/自己紹介',
    zh: '/简介',
    ko: '/소개',
  },
  '/elsewhere': {
    en: '/elsewhere',
    nl: '/elders',
    de: '/externe-links',
    fr: '/ailleurs',
    es: '/externos',
    it: '/altrove',
    pt: '/externos',
    hi: '/अन्यत्र',
    ja: '/外部',
    zh: '/站外',
    ko: '/외부',
  },
  '/organs': {
    en: '/organs',
    nl: '/orgels',
    de: '/orgeln',
    fr: '/orgues',
    es: '/organos',
    it: '/organi',
    pt: '/orgaos',
    hi: '/ऑर्गन',
    ja: '/オルガン',
    zh: '/管风琴',
    ko: '/오르간',
  },
  '/organs/[slug]': {
    en: '/organs/[slug]',
    nl: '/orgels/[slug]',
    de: '/orgeln/[slug]',
    fr: '/orgues/[slug]',
    es: '/organos/[slug]',
    it: '/organi/[slug]',
    pt: '/orgaos/[slug]',
    hi: '/ऑर्गन/[slug]',
    ja: '/オルガン/[slug]',
    zh: '/管风琴/[slug]',
    ko: '/오르간/[slug]',
  },
  '/scores': {
    en: '/scores',
    nl: '/partituren',
    de: '/noten',
    fr: '/partitions',
    es: '/partituras',
    it: '/spartiti',
    pt: '/partituras',
    hi: '/स्वरलिपि',
    ja: '/楽譜',
    zh: '/乐谱',
    ko: '/악보',
  },
  '/privacy': {
    en: '/privacy',
    nl: '/privacy',
    de: '/datenschutz',
    fr: '/confidentialite',
    es: '/privacidad',
    it: '/privacy',
    pt: '/privacidade',
    hi: '/गोपनीयता',
    ja: '/プライバシー',
    zh: '/隐私',
    ko: '/개인정보',
  },
  '/journal/[slug]': {
    en: '/journal/[slug]',
    nl: '/blog/[slug]',
    de: '/blog/[slug]',
    fr: '/blog/[slug]',
    es: '/blog/[slug]',
    it: '/blog/[slug]',
    pt: '/blog/[slug]',
    hi: '/ब्लॉग/[slug]',
    ja: '/ブログ/[slug]',
    zh: '/博客/[slug]',
    ko: '/일기/[slug]',
  },
  '/search': {
    en: '/search',
    nl: '/zoeken',
    de: '/suche',
    fr: '/recherche',
    es: '/buscar',
    it: '/cerca',
    pt: '/pesquisa',
    hi: '/खोज',
    ja: '/検索',
    zh: '/搜索',
    ko: '/검색',
  },
} as const satisfies Record<string, string | Record<Locale, string>>

/**
 * `next-intl` routing configuration.
 *
 * Strategy: prefix every URL with the locale, no exception. Visitors land
 * on `/{detected}/...` on first visit; the picker switches the prefix.
 *
 * `defaultLocale` is the "fall back when nothing matches" — we use the
 * UI default (English) per Q1 of the plan, since visitors who aren't
 * coming in with a recognisable Accept-Language are most likely to
 * understand English than Dutch.
 */
export const routing = defineRouting({
  locales: [...LOCALES],
  defaultLocale: UI_DEFAULT_LOCALE,
  localePrefix: 'always',
  pathnames,
})

export type RoutingLocale = Locale

/** Re-exported for ergonomic imports from app code. */
export { DEFAULT_LOCALE, LOCALES, UI_DEFAULT_LOCALE }
